### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [Shawydu/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Shawydu** [comment]
Thanks Ken, I google the "mobile meta tag" and add just one line to the file "application.html.erb", and everything changed to be amazing. Appreciate that!

**Comment by kenmazaika** [comment]
:+1: Looks perfect, Shawy.  Thumbs up!

**Comment by Shawydu** [comment]
Thanks Ken! Cheers!

2016-01-05 15:32 GMT-05:00 ken mazaika notifications@github.com:
